name: 'Update This PR'
description: 'Automatically add content to the top and/or bottom of a pr description.'
inputs:
  token:
    description: 'A Github access token'
    required: true
  top:
    description: 'What content to add to the top of the PR'
    required: false
    default: ""
  bottom:
    description: 'What content to add to the bottom of the PR'
    required: false
    default: ""
  from-branch:
    description: 'What regex to find in the branch name and add to top of the PR'
    required: false
    default: ""
runs:
  using: 'node16'
  main: 'dist/index.js'